import streamlit as st
from typing import Optional, Any
from models.narrative import Narrative
from models.pipeline_result import PipelineResult
from ai.narrative_generator import generate_investigative_narrative, generate_deterministic_narrative


def render_narrative(narrative: Optional[Any] = None, pipeline_result: Optional[PipelineResult] = None) -> None:
    """Render analyst-friendly investigative report with Gemini AI Narrative and deterministic fallback."""
    st.header("Forensic Narrative Report")
    st.caption("Factual digital evidence reconstruction and triage report grounded in RECOV pipeline telemetry.")

    result = pipeline_result
    if result is None and isinstance(narrative, PipelineResult):
        result = narrative
        narrative = getattr(result, "narrative", None)

    if not narrative and not result:
        st.info("No narrative report generated yet. Run pipeline analysis to inspect evidence.")
        return

    # Check session state for cached or newly generated AI narrative
    active_narrative = getattr(st.session_state, "ai_narrative_report", None) or narrative

    # AI Narrative Trigger Buttons
    col_btn, col_info = st.columns([1, 3])
    with col_btn:
        btn_label = "🔄 Regenerate Narrative" if (active_narrative and getattr(active_narrative, "is_ai_generated", False)) else "✨ Generate AI Narrative"
        if st.button(btn_label, type="primary", use_container_width=True):
            with st.spinner("Generating AI Narrative with Gemini 3.1 Flash-Lite..."):
                gen_res = generate_investigative_narrative(result or active_narrative)
                st.session_state.ai_narrative_report = gen_res
                active_narrative = gen_res

    with col_info:
        if active_narrative and getattr(active_narrative, "is_ai_generated", False):
            st.success(f"**AI-GENERATED NARRATIVE** | Model: `{active_narrative.ai_model or 'gemini-3.1-flash-lite'}`")
        elif active_narrative and getattr(active_narrative, "generation_error", None):
            st.warning(active_narrative.generation_error)

    st.markdown("---")

    # If AI Narrative was generated, render the 7 sections
    if active_narrative and getattr(active_narrative, "is_ai_generated", False) and active_narrative.executive_summary:
        st.subheader("AI Narrative Report")
        st.info("⚠️ **AI-GENERATED NARRATIVE:** Generated by Gemini 3.1 Flash-Lite based strictly on deterministic RECOV telemetry.")

        with st.container():
            st.markdown("#### 1. Executive Summary")
            st.markdown(active_narrative.executive_summary)

            st.markdown("#### 2. Evidence Overview")
            st.markdown(active_narrative.evidence_overview or "Not available from the RECOV results.")

            st.markdown("#### 3. Recovery Findings")
            st.markdown(active_narrative.recovery_findings or "Not available from the RECOV results.")

            st.markdown("#### 4. Integrity Assessment")
            st.markdown(active_narrative.integrity_assessment or "Not available from the RECOV results.")

            st.markdown("#### 5. Important Findings")
            st.markdown(active_narrative.important_findings or "Not available from the RECOV results.")

            st.markdown("#### 6. Limitations / Uncertainty")
            st.markdown(active_narrative.limitations or "Not available from the RECOV results.")

            st.markdown("#### 7. Analyst Conclusion")
            st.markdown(active_narrative.analyst_conclusion or "Not available from the RECOV results.")

        st.markdown("---")
        with st.expander("📊 Deterministic RECOV Report (Observed / Inferred / Unknown)", expanded=False):
            _render_deterministic_sections(active_narrative, result)
        return

    # Deterministic Narrative Display (Default / Fallback)
    st.subheader("Deterministic RECOV Report")
    _render_deterministic_sections(active_narrative, result)


def _render_deterministic_sections(narrative: Optional[Any], result: Optional[Any]) -> None:
    """Helper to render empirical Observed/Inferred/Unknown sections."""
    if narrative and isinstance(narrative, Narrative) and (narrative.observed or narrative.inferred):
        st.markdown("##### 1. Observed Facts")
        for item in narrative.observed:
            st.markdown(f"- {item}")

        st.markdown("##### 2. Forensic Inferences")
        for item in narrative.inferred:
            st.markdown(f"- {item}")

        st.markdown("##### 3. Unknown / Ambiguous Gaps")
        for item in narrative.unknown:
            st.markdown(f"- {item}")

        if getattr(narrative, "citations", None):
            st.markdown("##### 4. Evidence Citations")
            st.write(narrative.citations)
        return

    if result:
        det = generate_deterministic_narrative(result)
        st.markdown("##### 1. Observed Forensic Facts")
        for item in det.observed:
            st.markdown(f"- {item}")

        st.markdown("##### 2. Forensic Inferences & Diagnostics")
        for item in det.inferred:
            st.markdown(f"- {item}")

        st.markdown("##### 3. Technical Limitations & Gaps")
        for item in det.unknown:
            st.markdown(f"- {item}")
